# font

font_family      MesloLGS NF
bold_font        auto
italic_font      auto
bold_italic_font auto
# font-size 16.0

# symbol_map
symbol_map U+4E00-U+9FFF,U+3400-U+4DBF,U+20000-U+2A6DF,U+2A700–U+2B73F,U+2B740–U+2B81F,U+2B820–U+2CEAF,U+2CEB0-U+2EBEF,U+30000-U+3134F,U+31350-U+323AF,U+F900-U+FAFF,U+2F800-U+2FA1F PingFang SC

