--password-store=gnome-libsecret
--ozone-platform-hint=auto
--enable-wayland-ime
--enable-parallel-downloading=enabled
--enable-features=UseOzonePlatform,AcceleratedVideoDecodeLinuxGL,AcceleratedVideoDecodeLinuxZeroCopyGL,AcceleratedVideoEncoder
